/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trandpl.gui;

import java.io.File;
import java.io.FileNotFoundException;
import java.sql.SQLException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import trandpl.dao.ParticipantDAO;
import trandpl.dao.UserDAO;
import trandpl.pojo.CurrentUser;
import trandpl.pojo.ParticipantPojo;

public class PtEditProfileFrame extends javax.swing.JFrame  {    
   
    private File file;
    private String oldpwd,npwd,cnfpwd;
    public PtEditProfileFrame() {
        
        initComponents();
        this.setLocationRelativeTo(null);
        pwdPanel.setVisible(false);
        resumePanel.setVisible(false);
        loadData();
        
    }
    private void loadData(){
        try{
            ParticipantPojo pt=ParticipantDAO.getParticipantById(CurrentUser.getId());
            txtName.setText(pt.getName());
            txtMail.setText(pt.getUserId());
            txtPhone.setText(pt.getPhone());
        }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(null,"DB Error In Edit Profile", "Error!!",JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }
    private boolean validateInputs(){
        char []arroldpwd=txtPassword.getPassword();
        char []arrnpwd=txtNewPassword.getPassword();
        char []arrcnfrmpwd=txtCnfrmNewPassword.getPassword();
        if(arroldpwd.length==0||arrnpwd.length==0||arrcnfrmpwd.length==0)
            return false;
        oldpwd=String.valueOf(arroldpwd);
        npwd=String.valueOf(arrnpwd);
        cnfpwd=String.valueOf(arrcnfrmpwd);
        return true;
    }
    private boolean matchPasswords(){
        return npwd.equals(cnfpwd);
    }
            
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        resumePanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtFilePath = new javax.swing.JTextField();
        btnBrowse = new javax.swing.JButton();
        PhnLbl3 = new javax.swing.JLabel();
        chkResume = new javax.swing.JCheckBox();
        pwdPanel = new javax.swing.JPanel();
        txtNewPassword = new javax.swing.JPasswordField();
        txtCnfrmNewPassword = new javax.swing.JPasswordField();
        txtPassword = new javax.swing.JPasswordField();
        CurPwdBar = new javax.swing.JLabel();
        CurPwdLbl = new javax.swing.JLabel();
        NewPwdBar = new javax.swing.JLabel();
        NewPwdLbl = new javax.swing.JLabel();
        CnfNewPwdBar = new javax.swing.JLabel();
        CnfPwdLbl = new javax.swing.JLabel();
        chkPassword = new javax.swing.JCheckBox();
        txtMail = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        NameLbl = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        btnDiscard = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        PhnLbl = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        PhnLbl2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        PhnLbl1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(243, 246, 254));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 650, 940, 10));

        resumePanel.setOpaque(false);
        resumePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setForeground(new java.awt.Color(255, 0, 51));
        jLabel7.setText("* Upload resume in within 1000kb");
        resumePanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, -1));

        txtFilePath.setEditable(false);
        resumePanel.add(txtFilePath, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 570, 30));

        btnBrowse.setBackground(new java.awt.Color(174, 192, 236));
        btnBrowse.setText("Browse File");
        btnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseActionPerformed(evt);
            }
        });
        resumePanel.add(btnBrowse, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 20, 110, 30));

        jPanel1.add(resumePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 575, 850, 60));

        PhnLbl3.setFont(new java.awt.Font("Heiti SC", 1, 18)); // NOI18N
        PhnLbl3.setText("Want to change Resume");
        jPanel1.add(PhnLbl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 545, -1, -1));

        chkResume.setOpaque(false);
        chkResume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkResumeActionPerformed(evt);
            }
        });
        jPanel1.add(chkResume, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 545, 20, 20));

        pwdPanel.setOpaque(false);
        pwdPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNewPassword.setBackground(new java.awt.Color(173, 192, 234));
        txtNewPassword.setFont(new java.awt.Font("Heiti TC", 1, 18)); // NOI18N
        txtNewPassword.setBorder(null);
        pwdPanel.add(txtNewPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 63, 290, 30));

        txtCnfrmNewPassword.setBackground(new java.awt.Color(173, 192, 234));
        txtCnfrmNewPassword.setFont(new java.awt.Font("Heiti TC", 1, 18)); // NOI18N
        txtCnfrmNewPassword.setBorder(null);
        pwdPanel.add(txtCnfrmNewPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 290, 30));

        txtPassword.setBackground(new java.awt.Color(173, 192, 234));
        txtPassword.setFont(new java.awt.Font("Heiti TC", 1, 18)); // NOI18N
        txtPassword.setBorder(null);
        pwdPanel.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 7, 290, 30));

        CurPwdBar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/2021-12-23 00.04.59.png"))); // NOI18N
        pwdPanel.add(CurPwdBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 0, 340, -1));

        CurPwdLbl.setFont(new java.awt.Font("Heiti SC", 1, 18)); // NOI18N
        CurPwdLbl.setText("Current PassWord");
        pwdPanel.add(CurPwdLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 0, 203, 44));

        NewPwdBar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/2021-12-23 00.04.59.png"))); // NOI18N
        pwdPanel.add(NewPwdBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 56, 340, -1));

        NewPwdLbl.setFont(new java.awt.Font("Heiti SC", 1, 18)); // NOI18N
        NewPwdLbl.setText("New PassWord");
        pwdPanel.add(NewPwdLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 56, 203, 44));

        CnfNewPwdBar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/2021-12-23 00.04.59.png"))); // NOI18N
        pwdPanel.add(CnfNewPwdBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 112, 340, -1));

        CnfPwdLbl.setFont(new java.awt.Font("Heiti SC", 1, 18)); // NOI18N
        CnfPwdLbl.setText("Confirm New PassWord");
        pwdPanel.add(CnfPwdLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 112, -1, 44));

        jPanel1.add(pwdPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 340, 560, 170));

        chkPassword.setOpaque(false);
        chkPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkPasswordActionPerformed(evt);
            }
        });
        jPanel1.add(chkPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 295, 20, 20));

        txtMail.setEditable(false);
        txtMail.setBackground(new java.awt.Color(173, 192, 234));
        txtMail.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtMail.setText("neelesh1210@gmail.com");
        txtMail.setBorder(null);
        txtMail.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(txtMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 477, 280, 30));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/2021-12-23 00.04.59.png"))); // NOI18N
        jLabel12.setText("jLabel6");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 470, 330, -1));

        NameLbl.setFont(new java.awt.Font("Heiti SC", 1, 18)); // NOI18N
        NameLbl.setText("Name :-");
        jPanel1.add(NameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, -1, -1));

        txtName.setEditable(false);
        txtName.setBackground(new java.awt.Color(173, 192, 234));
        txtName.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtName.setText("neelesh mehar");
        txtName.setBorder(null);
        txtName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 317, 280, 30));

        btnDiscard.setBackground(new java.awt.Color(172, 194, 236));
        btnDiscard.setText("Discard changes");
        btnDiscard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiscardActionPerformed(evt);
            }
        });
        jPanel1.add(btnDiscard, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 670, 170, 30));

        btnSave.setBackground(new java.awt.Color(172, 194, 236));
        btnSave.setText("Save Changes");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 670, 170, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/2021-12-23 00.04.59.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 330, -1));

        txtPhone.setEditable(false);
        txtPhone.setBackground(new java.awt.Color(173, 192, 234));
        txtPhone.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtPhone.setText("8871414187");
        txtPhone.setBorder(null);
        txtPhone.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneActionPerformed(evt);
            }
        });
        jPanel1.add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 397, 280, 30));

        PhnLbl.setFont(new java.awt.Font("Heiti SC", 1, 18)); // NOI18N
        PhnLbl.setText("Phone no :-");
        jPanel1.add(PhnLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/2021-12-23 00.04.59.png"))); // NOI18N
        jLabel11.setText("jLabel6");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, 330, -1));

        PhnLbl2.setFont(new java.awt.Font("Heiti SC", 1, 18)); // NOI18N
        PhnLbl2.setText("Mail Address :-");
        jPanel1.add(PhnLbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 450, -1, -1));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, 20, 240));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 970, 10));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/World-Map.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 970, 200));

        PhnLbl1.setFont(new java.awt.Font("Heiti SC", 1, 18)); // NOI18N
        PhnLbl1.setText("Want to change password ");
        jPanel1.add(PhnLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, -1, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/transparent logo.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 180, -1));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 530, 940, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1080, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneActionPerformed

    private void chkPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkPasswordActionPerformed
       
       
        if(chkPassword.isSelected()){
            pwdPanel.setVisible(true);  
        }
        else{
            pwdPanel.setVisible(false);
        }
    }//GEN-LAST:event_chkPasswordActionPerformed

    private void chkResumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkResumeActionPerformed
       
        if(chkResume.isSelected()){
            resumePanel.setVisible(true);  
        }
        else{
            resumePanel.setVisible(false);
        }
    }//GEN-LAST:event_chkResumeActionPerformed

    private void btnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseActionPerformed
       JFileChooser fileChooser=new JFileChooser();
       fileChooser.setDialogTitle("Select Your Resume");
       fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
       int result=fileChooser.showOpenDialog(null);
       if(result==JFileChooser.APPROVE_OPTION){
           file=fileChooser.getSelectedFile();
           txtFilePath.setText(file.getName());
       }
       
    }//GEN-LAST:event_btnBrowseActionPerformed

    private void btnDiscardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiscardActionPerformed
        new ParticipantsOptionFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDiscardActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
       
        boolean pwdChanged=false,resumeUpdated=false;
        if(chkPassword.isSelected()){
            if(validateInputs()==false){
                JOptionPane.showMessageDialog(null, "Please Fill All The Fields","Empty Fields",JOptionPane.WARNING_MESSAGE);
                return;
            }
            if(matchPasswords()==false){
                JOptionPane.showMessageDialog(null, "Password And Confirm Password Do Not Match!","Password Mismatching",JOptionPane.WARNING_MESSAGE);
                return;
            }
            try{
                boolean resp=UserDAO.checkOldPassword(CurrentUser.getId(),oldpwd);
                if(resp==true){
                    UserDAO.updateParticipantPassword(CurrentUser.getId(), npwd);
                    pwdChanged=true;
                }else{
                   JOptionPane.showMessageDialog(null, "Your Old Password Is Wrong!","Password Mismatching",JOptionPane.WARNING_MESSAGE);
               }
            }
            catch(SQLException ex){
            JOptionPane.showMessageDialog(null,"DB Error In Edit Profile", "Error!!",JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
            }
            
        }
        if(chkResume.isSelected()){
            if(txtFilePath.getText().trim()!=""){
                
            try{
                ParticipantDAO.updateResume(CurrentUser.getId(), file);
                resumeUpdated=true;
                
            }
            catch(SQLException ex){
            JOptionPane.showMessageDialog(null,"DB Error In Edit Profile", "Error!!",JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
            }
            catch(FileNotFoundException ex){
            JOptionPane.showMessageDialog(null,"File Error In Edit Profile", "Error!!",JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
            }
         }
       }
      if(pwdChanged && resumeUpdated){
          JOptionPane.showMessageDialog(null, "Password & Resume Updated Successfully!","Success",JOptionPane.INFORMATION_MESSAGE);
      }
      else if(pwdChanged){
          JOptionPane.showMessageDialog(null, "Password Updated Successfully!","Success",JOptionPane.INFORMATION_MESSAGE);
      }
      else if(resumeUpdated){
          JOptionPane.showMessageDialog(null, "Resume Updated Successfully!","Success",JOptionPane.INFORMATION_MESSAGE);
      }
      else{
          JOptionPane.showMessageDialog(null, "No Changes Done!!","Message!",JOptionPane.INFORMATION_MESSAGE);
      }
    }//GEN-LAST:event_btnSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PtEditProfileFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PtEditProfileFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PtEditProfileFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PtEditProfileFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PtEditProfileFrame().setVisible(true);
            }
        });
    }
   
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CnfNewPwdBar;
    private javax.swing.JLabel CnfPwdLbl;
    private javax.swing.JLabel CurPwdBar;
    private javax.swing.JLabel CurPwdLbl;
    private javax.swing.JLabel NameLbl;
    private javax.swing.JLabel NewPwdBar;
    private javax.swing.JLabel NewPwdLbl;
    private javax.swing.JLabel PhnLbl;
    private javax.swing.JLabel PhnLbl1;
    private javax.swing.JLabel PhnLbl2;
    private javax.swing.JLabel PhnLbl3;
    private javax.swing.JButton btnBrowse;
    private javax.swing.JButton btnDiscard;
    private javax.swing.JButton btnSave;
    private javax.swing.JCheckBox chkPassword;
    private javax.swing.JCheckBox chkResume;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JPanel pwdPanel;
    private javax.swing.JPanel resumePanel;
    private javax.swing.JPasswordField txtCnfrmNewPassword;
    private javax.swing.JTextField txtFilePath;
    private javax.swing.JTextField txtMail;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtNewPassword;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables
}
